Repository biswapcom/biswap-front-uikit, pull requests merged in 2023-03, with the labels that each got.

#595 Bsw 3473
  dist/index.cjs.js
  dist/index.esm.js
  dist/widgets/Menu/components/Footer/BuyBSW.d.ts
  dist/widgets/Menu/components/Footer/FoolerInfo.d.ts
  dist/widgets/Menu/components/Footer/Footer.d.ts
  dist/widgets/Menu/types.d.ts
  dist/widgets/Toast/types.d.ts
  src/widgets/Menu/Menu.tsx
  src/widgets/Menu/components/Footer/BuyBSW.tsx
  src/widgets/Menu/components/Footer/FoolerInfo.tsx
  src/widgets/Menu/components/Footer/Footer.tsx
  src/widgets/Menu/index.stories.tsx
  src/widgets/Menu/types.ts
  src/widgets/Toast/Toast.tsx
  src/widgets/Toast/ToastContainer.tsx
  src/widgets/Toast/index.stories.tsx
  src/widgets/Toast/types.ts
Labels: improvements

#600 Bsw 3506 faq
  dist/components/Faqs/FaqAccordion/index.d.ts
  dist/components/Faqs/Faqs.d.ts
  dist/components/Faqs/theme.d.ts
  dist/components/Faqs/types.d.ts
  dist/index.cjs.js
  dist/index.esm.js
  src/components/Faqs/FaqAccordion/index.tsx
  src/components/Faqs/Faqs.tsx
  src/components/Faqs/index.stories.tsx
  src/components/Faqs/theme.ts
  src/components/Faqs/types.ts
Labels: improvements

#601 add badge buttons
  dist/components/BadgeButton/BadgeButton.d.ts
  dist/components/BadgeButton/index.d.ts
  dist/components/BadgeButton/theme.d.ts
  dist/components/BadgeButton/types.d.ts
  dist/index.cjs.js
  dist/index.d.ts
  dist/index.esm.js
  dist/theme/colors.d.ts
  dist/theme/types.d.ts
  src/components/BadgeButton/BadgeButton.tsx
  src/components/BadgeButton/index.stories.tsx
  src/components/BadgeButton/index.tsx
  src/components/BadgeButton/theme.ts
  src/components/BadgeButton/types.ts
  src/components/TooltipHelper/ToolipHelper.tsx
  src/components/TooltipHelper/config.tsx
  src/index.ts
  src/theme/colors.ts
  src/theme/types.ts
Labels: new feature

#609 add social link
  dist/components/Svg/Icons/Socials/Quora.d.ts
  dist/components/Svg/index.d.ts
  dist/index.cjs.js
  dist/index.esm.js
  src/components/Svg/Icons/Socials/Quora.tsx
  src/components/Svg/index.tsx
  src/widgets/Menu/components/Footer/Community.tsx
  src/widgets/Menu/components/Footer/Footer.tsx
  src/widgets/Menu/config.ts
Labels: dependencies

#599 Bsw 3473 Locatizations
  dist/index.cjs.js
  dist/index.esm.js
  dist/widgets/Menu/components/Footer/BuyBSW.d.ts
  dist/widgets/Menu/components/Footer/FoolerInfo.d.ts
  dist/widgets/Menu/components/Footer/Footer.d.ts
  dist/widgets/Menu/types.d.ts
  dist/widgets/Toast/types.d.ts
  src/widgets/Menu/Menu.tsx
  src/widgets/Menu/components/Footer/BuyBSW.tsx
  src/widgets/Menu/components/Footer/FoolerInfo.tsx
  src/widgets/Menu/components/Footer/Footer.tsx
  src/widgets/Menu/index.stories.tsx
  src/widgets/Menu/types.ts
  src/widgets/Toast/Toast.tsx
  src/widgets/Toast/ToastContainer.tsx
  src/widgets/Toast/index.stories.tsx
  src/widgets/Toast/types.ts
Labels: improvements
